"""add like_count

Revision ID: 055484e9f8cd
Revises: 0c65b7d42c82
Create Date: 2025-05-12 16:38:16.391548

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '055484e9f8cd'
down_revision = '0c65b7d42c82'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('posts', sa.Column('like_count', sa.Integer(), nullable=False, server_default='0'))
    # Remove the server_default after the column is created, if you don't want it for future inserts:
    op.alter_column('posts', 'like_count', server_default=None)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('posts', 'like_count')
    # ### end Alembic commands ###
