"""media count

Revision ID: 1339ea2e0db6
Revises: c2bbb554076e
Create Date: 2025-05-26 08:31:25.673429

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '1339ea2e0db6'
down_revision = 'c2bbb554076e'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('isFollowedByCurrentUser', sa.Boolean(), nullable=True))
    op.add_column('users', sa.Column('postsCount', sa.Integer(), nullable=True))
    op.add_column('users', sa.Column('reelsCount', sa.Integer(), nullable=True))
    op.add_column('users', sa.Column('storiesCount', sa.Integer(), nullable=True))
    op.add_column('users', sa.Column('hasActiveStory', sa.Boolean(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'hasActiveStory')
    op.drop_column('users', 'storiesCount')
    op.drop_column('users', 'reelsCount')
    op.drop_column('users', 'postsCount')
    op.drop_column('users', 'isFollowedByCurrentUser')
    # ### end Alembic commands ###
