"""remove foll counts

Revision ID: 9dba40f397f4
Revises: f88634a7408d
Create Date: 2025-05-26 10:10:27.881591

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '9dba40f397f4'
down_revision = 'f88634a7408d'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'following_count')
    op.drop_column('users', 'followers_count')
    op.drop_column('users', 'is_followed_by_current_user')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('is_followed_by_current_user', sa.BOOLEAN(), autoincrement=False, nullable=True))
    op.add_column('users', sa.Column('followers_count', sa.INTEGER(), autoincrement=False, nullable=True))
    op.add_column('users', sa.Column('following_count', sa.INTEGER(), autoincrement=False, nullable=True))
    # ### end Alembic commands ###
