"""relationship between notif and reel

Revision ID: ac02e92e40bc
Revises: f19d513ecaa2
Create Date: 2025-05-24 23:40:12.239248

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ac02e92e40bc'
down_revision = 'f19d513ecaa2'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
