"""follows count

Revision ID: c2bbb554076e
Revises: 16e59be828b9
Create Date: 2025-05-26 08:27:17.126561

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c2bbb554076e'
down_revision = '16e59be828b9'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('followersCount', sa.Integer(), nullable=True))
    op.add_column('users', sa.Column('followingCount', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'followingCount')
    op.drop_column('users', 'followersCount')
    # ### end Alembic commands ###
