"""adding comment count to post

Revision ID: c907eba9d25e
Revises: fbba5332c287
Create Date: 2025-05-13 15:49:00.854430

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.sql import text


# revision identifiers, used by Alembic.
revision = 'c907eba9d25e'
down_revision = 'fbba5332c287'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # Step 1: Add the column as nullable first
    op.add_column('posts', sa.Column('comment_count', sa.Integer(), nullable=True))

    # Step 2: Update existing rows to set comment_count to 0
    op.execute(text("UPDATE posts SET comment_count = 0"))

    # Step 3: Alter the column to make it NOT NULL
    op.alter_column('posts', 'comment_count', nullable=False, existing_type=sa.Integer())


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('posts', 'comment_count')
    # ### end Alembic commands ###
