"""comm owner

Revision ID: cda9af4a9359
Revises: 9dba40f397f4
Create Date: 2025-05-26 10:33:10.535043

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'cda9af4a9359'
down_revision = '9dba40f397f4'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
