"""adding counts to reel

Revision ID: e73c5335d4bc
Revises: f16b5f665604
Create Date: 2025-05-24 23:02:49.992889

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e73c5335d4bc'
down_revision = 'f16b5f665604'
branch_labels = None
depends_on = None


def upgrade():
    op.add_column('reels', sa.Column('like_count', sa.Integer(), nullable=False, server_default='0'))
    op.add_column('reels', sa.Column('comment_count', sa.Integer(), nullable=False, server_default='0'))


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('reels', 'comment_count')
    op.drop_column('reels', 'like_count')
    # ### end Alembic commands ###
