"""adding like com to reel

Revision ID: f16b5f665604
Revises: c907eba9d25e
Create Date: 2025-05-24 22:48:22.529109

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f16b5f665604'
down_revision = 'c907eba9d25e'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('comments', sa.Column('reel_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'comments', 'reels', ['reel_id'], ['id'])
    op.add_column('likes', sa.Column('reel_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'likes', 'reels', ['reel_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'likes', type_='foreignkey')
    op.drop_column('likes', 'reel_id')
    op.drop_constraint(None, 'comments', type_='foreignkey')
    op.drop_column('comments', 'reel_id')
    # ### end Alembic commands ###
