"""adding reel id to notify

Revision ID: f19d513ecaa2
Revises: ab8c42edfd9f
Create Date: 2025-05-24 23:38:06.507700

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f19d513ecaa2'
down_revision = 'ab8c42edfd9f'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('notifications', sa.Column('reel_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'notifications', 'reels', ['reel_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'notifications', type_='foreignkey')
    op.drop_column('notifications', 'reel_id')
    # ### end Alembic commands ###
