"""follows count5

Revision ID: f88634a7408d
Revises: 1339ea2e0db6
Create Date: 2025-05-26 08:39:46.217826

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f88634a7408d'
down_revision = '1339ea2e0db6'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('followers_count', sa.Integer(), nullable=True))
    op.add_column('users', sa.Column('following_count', sa.Integer(), nullable=True))
    op.add_column('users', sa.Column('is_followed_by_current_user', sa.Boolean(), nullable=True))
    op.add_column('users', sa.Column('posts_count', sa.Integer(), nullable=True))
    op.add_column('users', sa.Column('reels_count', sa.Integer(), nullable=True))
    op.add_column('users', sa.Column('stories_count', sa.Integer(), nullable=True))
    op.add_column('users', sa.Column('has_active_story', sa.Boolean(), nullable=True))
    op.drop_column('users', 'storiesCount')
    op.drop_column('users', 'isFollowedByCurrentUser')
    op.drop_column('users', 'hasActiveStory')
    op.drop_column('users', 'reelsCount')
    op.drop_column('users', 'followingCount')
    op.drop_column('users', 'followersCount')
    op.drop_column('users', 'postsCount')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('postsCount', sa.INTEGER(), autoincrement=False, nullable=True))
    op.add_column('users', sa.Column('followersCount', sa.INTEGER(), autoincrement=False, nullable=True))
    op.add_column('users', sa.Column('followingCount', sa.INTEGER(), autoincrement=False, nullable=True))
    op.add_column('users', sa.Column('reelsCount', sa.INTEGER(), autoincrement=False, nullable=True))
    op.add_column('users', sa.Column('hasActiveStory', sa.BOOLEAN(), autoincrement=False, nullable=True))
    op.add_column('users', sa.Column('isFollowedByCurrentUser', sa.BOOLEAN(), autoincrement=False, nullable=True))
    op.add_column('users', sa.Column('storiesCount', sa.INTEGER(), autoincrement=False, nullable=True))
    op.drop_column('users', 'has_active_story')
    op.drop_column('users', 'stories_count')
    op.drop_column('users', 'reels_count')
    op.drop_column('users', 'posts_count')
    op.drop_column('users', 'is_followed_by_current_user')
    op.drop_column('users', 'following_count')
    op.drop_column('users', 'followers_count')
    # ### end Alembic commands ###
