"""adding replies to comment

Revision ID: fbba5332c287
Revises: 055484e9f8cd
Create Date: 2025-05-13 15:22:09.999191

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'fbba5332c287'
down_revision = '055484e9f8cd'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
